# Generated by Django 4.1 on 2023-12-20 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_alter_currentmeasurement_current_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentmeasurement",
            name="measurement_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
