# Generated by Django 4.1 on 2023-12-16 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worklog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="work_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 16, 7, 53, 14, 663583, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
