# Generated by Django 4.1 on 2023-12-16 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worklog", "0002_alter_worklog_work_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklog",
            name="work_type",
            field=models.CharField(
                choices=[("installation", "設置"), ("removal", "撤去"), ("other", "その他")],
                default="installation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="work_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 16, 8, 32, 3, 406200, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
