# Generated by Django 4.1 on 2023-12-16 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("worklog", "0003_worklog_work_type_alter_worklog_work_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="work_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
