# Generated by Django 4.1 on 2023-12-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rack_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ups_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PowerSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_system_number", models.IntegerField()),
                (
                    "supply_rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.rack"
                    ),
                ),
                (
                    "supply_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.ups"
                    ),
                ),
            ],
        ),
    ]
