# Generated by Django 4.1 on 2024-01-25 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('ups_number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSystem',
            fields=[
                ('power_system_number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('max_current', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('supply_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.rack')),
                ('supply_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ups')),
            ],
        ),
    ]
