# Generated by Django 4.1 on 2024-01-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ups',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
